// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Customer struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Phonenumber int      `json:"Phonenumber"`
	Email       string   `json:"Email"`
	Orders      []*Order `json:"orders"`
}

type Order struct {
	ID              string    `json:"id"`
	Customer        *Customer `json:"customer"`
	Item            []string  `json:"item"`
	Price           float64   `json:"price"`
	DateOrderPlaced time.Time `json:"date_order_placed"`
}

type CustomerInput struct {
	Name        string `json:"name"`
	Phonenumber int    `json:"Phonenumber"`
	Email       string `json:"Email"`
}

type OrderInput struct {
	Item            []string  `json:"item"`
	Price           float64   `json:"price"`
	DateOrderPlaced time.Time `json:"date_order_placed"`
}
